### ISSUE TITLE
CanCarryItem

### ISSUE THREAD

**Issue by FPS-86** [kloudzxc/kloud-farmjob#2]
Greetings. I get an error when I try to collect resources

```
[script:kloud-farmjob] SCRIPT ERROR: @kloud-farmjob/server.lua:8: attempt to call a nil value (global 'CanCarryItem')
[script:kloud-farmjob] > callbackResponse (@ox_lib/imports/callback/server.lua:60)
[script:kloud-farmjob] > handler (@ox_lib/imports/callback/server.lua:76)
```

ESX version 1.10.1

**Comment by FPS-86** [comment]
Bullshit is not working :)

**Comment by kloudzxc** [comment]
start inventory script before kloud-farmjob. reading the instructions first will definitely hurt you

**Comment by FPS-86** [comment]
Thank you, I solved the problem. Reconfigured the server from scratch and it worked.
