### ISSUE TITLE
Issue #1 not resolved

### ISSUE THREAD

**Issue by AntonMars** [kloudzxc/kloud-farmjob#3]
I don't think you resolve issues by just closing them without any comment. I refer to issue #1 
Have you made any changes and can I download the update or not?
Please comment and allow me a chance to agree that the issue is resolved before closing it again!

**Comment by AntonMars** [comment]
Apologies, I revisited the repo and noticed you had changed the zone to a sphere.
So, can't you get the box zone to work?
None of the farm fields are round, so being able to poly (or at least box) an area is probably more important than using a sphere to define the area. Please see if you can figure this out. I haven't got enough coding knowledge to do it, otherwise I would have done it already.

**Comment by kloudzxc** [comment]
Will change it

**Comment by kloudzxc** [comment]
fixed with v1.2.0
